##
# Redirect "/" to monocle preview

-
  name:  'Redirect to Monocle'
  uriPattern: ''
  defaults:
    '@package': 'CRON.MonoclePreviewSite'
    '@subpackage': ''
    '@controller': 'Redirect'
    '@action': 'redirect'
  httpMethods: ['GET','POST']
