##
# Redirect "/" to monocle preview

-
  name:  'Redirect to Monocle'
  uriPattern: ''
  defaults:
    '@package': 'CRON.MonoclePreviewSite'
    '@subpackage': ''
    '@controller': 'Redirect'
    '@action': 'redirect'
  httpMethods: ['GET','POST']

##
# Simplified monocle route ("/preview" instead of "/monocle/preview/module")

-
  name:  'Monocle Preview - Module'
  uriPattern: 'preview'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@action': 'index'
    '@controller': 'Module'
    '@format': 'html'
  httpMethods: ['GET','POST']
